.\" PsBrowser manpage.
.\" Copyright (C) 2010 Samuel Ribeiro da Costa Vale <srcvale@minaslivre.org>
.\" Released as GPLv3+
.TH psbrowser 1 "August 24th 2010" "COMUM.ORG" ""
.SH NAME
PsBrowser \- Browse your PubSub service and publish content.

.SH SYNOPSIS
.B psbrowser

.SH DESCRIPTION
.I PsBrowser
aims to be a generic tool for browsing and publishing content in an XMPP
implementation of a Pubsub service. It uses the Taningia library that implements
an XMPP client and provides a Pubsub API. Implemented features:
.PP
 * Multiple connections through a bookmark manager;
 * A nice tree view to list nodes recursively;
 * Node creation (and configuration);
 * Node deletion;
 * List of node items;
.PP
All this Pubsub stuff is specified in the XEP 0060 document -
http://xmpp.org/extensions/xep-0060.html .

.SH DEVELOPMENT, BUGS
Visit http://projects.comum.org/psbrowser/ for new releases, development stuff
and bug report.

.SH AUTHOR
Software written by Lincoln de Sousa. This manual page was written by Samuel Ribeiro da Costa Vale.
